# Render Blueprint: Postgres + FastAPI backend + Vite frontend

databases:
  - name: gs-postgres
    plan: free
    databaseName: appdb
    user: postgresuser

services:
  # Backend API (FastAPI)
  - type: web
    name: access-control-backend
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --app-dir backend
    healthCheckPath: /docs
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gs-postgres
          property: postgresql://postgresuser:YdRQMhzvCgSdE2oGeKVZwYLxqj7CdiTk@dpg-d2qq9cbe5dus73ce5e90-a.oregon-postgres.render.com/appdb_iwav
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
      # Allow the deployed frontend origin
      - key: CORS_ORIGINS
        fromService:
          name: access-control-frontend
          property: url

  # Frontend (Vite -> Static Site)
  - type: static
    name: access-control-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      # Build-time API base URL used by Vite
      - key: VITE_API_URL
        fromService:
          name: access-control-backend
          property: url
